USE alternatech;
-- Fictional demonstration companies and vacancies; stable IDs make reruns safe.
START TRANSACTION;
INSERT INTO companies (id,name,description) VALUES (1,'Loire Digital Studio','Fictional French technology company supporting junior talent.') ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description);
INSERT INTO companies (id,name,description) VALUES (2,'Anjou Data Lab','Fictional French technology company supporting junior talent.') ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description);
INSERT INTO companies (id,name,description) VALUES (3,'Armor Cyber Solutions','Fictional French technology company supporting junior talent.') ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description);
INSERT INTO companies (id,name,description) VALUES (4,'Paris AI Atelier','Fictional French technology company supporting junior talent.') ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description);
INSERT INTO companies (id,name,description) VALUES (5,'Atlantic Cloud Systems','Fictional French technology company supporting junior talent.') ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description);
INSERT INTO categories (id,name) VALUES (1,'Development') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (id,name) VALUES (2,'Data') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (id,name) VALUES (3,'Artificial Intelligence') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (id,name) VALUES (4,'Cybersecurity') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (id,name) VALUES (5,'Cloud') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (1,1,1,'PHP Developer','Join a supportive development team in Nantes. Build practical skills through mentoring and real project work.','PHP Developer — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic development skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Nantes','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (2,2,2,'Data Analyst','Join a supportive data team in Angers. Build practical skills through mentoring and real project work.','Data Analyst — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic data skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Angers','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (3,3,3,'Machine Learning Engineer','Join a supportive artificial intelligence team in Rennes. Build practical skills through mentoring and real project work.','Machine Learning Engineer — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic artificial intelligence skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Rennes','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (4,4,4,'SOC Analyst','Join a supportive cybersecurity team in Paris. Build practical skills through mentoring and real project work.','SOC Analyst — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cybersecurity skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Paris','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (5,5,5,'Cloud Engineer','Join a supportive cloud team in Lyon. Build practical skills through mentoring and real project work.','Cloud Engineer — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cloud skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Lyon','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (6,1,1,'Frontend Developer','Join a supportive development team in Angers. Build practical skills through mentoring and real project work.','Frontend Developer — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic development skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Angers','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (7,2,2,'Data Engineer','Join a supportive data team in Rennes. Build practical skills through mentoring and real project work.','Data Engineer — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic data skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Rennes','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (8,3,3,'AI Application Developer','Join a supportive artificial intelligence team in Paris. Build practical skills through mentoring and real project work.','AI Application Developer — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic artificial intelligence skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Paris','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (9,4,4,'Security Consultant','Join a supportive cybersecurity team in Lyon. Build practical skills through mentoring and real project work.','Security Consultant — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cybersecurity skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Lyon','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (10,5,5,'DevOps Engineer','Join a supportive cloud team in Nantes. Build practical skills through mentoring and real project work.','DevOps Engineer — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cloud skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Nantes','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (11,1,1,'Full Stack Developer','Join a supportive development team in Rennes. Build practical skills through mentoring and real project work.','Full Stack Developer — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic development skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Rennes','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (12,2,2,'BI Analyst','Join a supportive data team in Paris. Build practical skills through mentoring and real project work.','BI Analyst — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic data skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Paris','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (13,3,3,'NLP Research Assistant','Join a supportive artificial intelligence team in Lyon. Build practical skills through mentoring and real project work.','NLP Research Assistant — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic artificial intelligence skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Lyon','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (14,4,4,'Network Security Analyst','Join a supportive cybersecurity team in Nantes. Build practical skills through mentoring and real project work.','Network Security Analyst — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cybersecurity skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Nantes','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (15,5,5,'Platform Engineer','Join a supportive cloud team in Angers. Build practical skills through mentoring and real project work.','Platform Engineer — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cloud skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Angers','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (16,1,1,'Backend Developer','Join a supportive development team in Paris. Build practical skills through mentoring and real project work.','Backend Developer — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic development skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Paris','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (17,2,2,'Analytics Engineer','Join a supportive data team in Lyon. Build practical skills through mentoring and real project work.','Analytics Engineer — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic data skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Lyon','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (18,3,3,'Computer Vision Intern','Join a supportive artificial intelligence team in Nantes. Build practical skills through mentoring and real project work.','Computer Vision Intern — Junior CDI
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic artificial intelligence skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Nantes','Junior CDI','€32,000–38,000/year','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (19,4,4,'Cybersecurity Engineer','Join a supportive cybersecurity team in Angers. Build practical skills through mentoring and real project work.','Cybersecurity Engineer — Alternance
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cybersecurity skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Angers','Alternance','According to French alternance scale','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
INSERT INTO advertisements (id,company_id,category_id,title,short_description,description,location,contract_type,salary,working_time) VALUES (20,5,5,'Cloud Support Engineer','Join a supportive cloud team in Rennes. Build practical skills through mentoring and real project work.','Cloud Support Engineer — Stage
Work alongside experienced engineers on internal tools and client projects. Participate in code reviews, documentation and team demonstrations.
Profile: studying computing or recently graduated; curiosity, clear communication and basic cloud skills. French B2 and technical English preferred.
Mentoring, structured onboarding and two remote days per week. This is a fictional demonstration vacancy.','Rennes','Stage','€900–1,200/month','35 hours/week') ON DUPLICATE KEY UPDATE title=VALUES(title),short_description=VALUES(short_description),description=VALUES(description),location=VALUES(location),contract_type=VALUES(contract_type),salary=VALUES(salary),working_time=VALUES(working_time);
COMMIT;
